article/urls.py
from django.conf.urls import patterns, include, url
from api import ArticleResource

article_resource = ArticleResource()

urlpatterns = patterns('',
    url(r'^all/$', 'article.views.articles'),
    url(r'^get/(?P<article_id>\d+)/$', 'article.views.article'),
    url(r'^language/(?P<language>[a-z\-]+)/$', 'article.views.language'),
    url(r'^create/$', 'article.views.create'),
    url(r'^like/(?P<article_id>\d+)/$', 'article.views.like_article'),
    url(r'^add_comment/(?P<article_id>\d+)/$', 'article.views.add_comment'),
    url(r'^search/$', 'article.views.search_titles'),
    url(r'^api/', include(article_resource.urls)),
)

django_test/urls.py
from django.conf.urls import patterns, include, url
#from django.contrib.auth.views import login, logout

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

from django_test.forms import ContactForm1, ContactForm2, ContactForm3
from django_test.views import ContactWizard

import settings

urlpatterns = patterns('',
    (r'^articles/', include('article.urls')),
    (r'^accounts/', include('userprofile.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    
    # user auth urls
    url(r'^accounts/login/$',  'django_test.views.login'),
    url(r'^accounts/auth/$',  'django_test.views.auth_view'),    
    url(r'^accounts/logout/$', 'django_test.views.logout'),
    url(r'^accounts/loggedin/$', 'django_test.views.loggedin'),
    url(r'^accounts/invalid/$', 'django_test.views.invalid_login'),    
    url(r'^accounts/register/$', 'django_test.views.register_user'),
    url(r'^accounts/register_success/$', 'django_test.views.register_success'),
    url(r'^contact/$', ContactWizard.as_view([ContactForm1, ContactForm2, ContactForm3])),
    url(r'^search/', include('haystack.urls')),
)

if not settings.DEBUG:
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
   
    urlpatterns += staticfiles_urlpatterns()

article/models.py
from django.db import models
from time import time
import os
from django.db.models import signals
from django.conf import settings
import os.path
from django_test import settings



def get_upload_file_name(instance, filename):
    return settings.UPLOAD_FILE_PATTERN % (str(time()).replace('.','_'), filename)
    
# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=200)
    body = models.TextField()
    pub_date = models.DateTimeField('date published')
    likes = models.IntegerField(default=0)
    thumbnail = models.FileField(upload_to=get_upload_file_name)

    
    def __unicode__(self):
        return self.title
    
    def get_absolute_url(self):
        return "/articles/get/%i/" % self.id  
    
    def get_thumbnail(self):
        thumb = str(self.thumbnail)
        if not settings.DEBUG:
            thumb = thumb.replace('assets/', '')
            
        return thumb
        
    
    
class Comment(models.Model):
    first_name = models.CharField(max_length=200)
    second_name = models.CharField(max_length=200)
    body = models.TextField()
    pub_date = models.DateTimeField('date published')
    article = models.ForeignKey(Article)
    
    

article/forms.py
from django import forms
from models import Article, Comment

class ArticleForm(forms.ModelForm):  

    class Meta:
        model = Article
        fields = ('title', 'body', 'pub_date', 'thumbnail')

class CommentForm(forms.ModelForm):
    
    class Meta:
        model = Comment
        fields = ('first_name', 'second_name', 'body')

article/views.py
from django.shortcuts import render_to_response
from article.models import Article, Comment
from django.http import HttpResponse
from forms import ArticleForm, CommentForm
from django.http import HttpResponseRedirect
from django.core.context_processors import csrf
from django.utils import timezone
from django.conf import settings
from haystack.query import SearchQuerySet

import logging
    
logr = logging.getLogger(__name__)

# Create your views here.


def articles(request):
    language = 'en-gb'
    session_language = 'en-gb'
    
    if 'lang' in request.COOKIES:
        language = request.COOKIES['lang']
        
    if 'lang' in request.session:
        session_language = request.session['lang']
        
    args = {}
    args.update(csrf(request))
    
    args['articles'] = Article.objects.all()
    args['language'] = language   
    args['session_language'] = session_language 
    
    return render_to_response('articles.html', args) 


def article(request, article_id=1):   
    return render_to_response('article.html', 
                              {'article': Article.objects.get(id=article_id) })


def language(request, language='en-gb'):
    response = HttpResponse("setting language to %s" % language)
    
    response.set_cookie('lang', language)
    
    request.session['lang'] = language
    
    return response

def create(request):
    if request.POST:
        form = ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            a = form.save()
            ix = open_dir(settings.WHOOSH_INDEX)
            
            writer = ix.writer()

            writer.add_document(title=a.title, body=a.body,
                                        url=unicode(a.get_absolute_url()))
            writer.commit()
        
            return HttpResponseRedirect('/articles/all')
    else:
        form = ArticleForm()
        
    args = {}
    args.update(csrf(request))
    
    args['form'] = form
    
    return render_to_response('create_article.html', args)
        
def like_article(request, article_id):
    if article_id:
        a = Article.objects.get(id=article_id)
        count = a.likes
        count += 1
        a.likes = count
        a.save()
        
    return HttpResponseRedirect('/articles/get/%s' % article_id)
        
def add_comment(request, article_id):
    a = Article.objects.get(id=article_id)
    
    if request.method == "POST":
        f = CommentForm(request.POST)
        if f.is_valid():
            c = f.save(commit=False)
            c.pub_date = timezone.now()
            c.article = a
            c.save()
            
            return HttpResponseRedirect('/articles/get/%s' % article_id)
        
    else:
        f = CommentForm()

    args = {}
    args.update(csrf(request))
    
    args['article'] = a
    args['form'] = f
    
    return render_to_response('add_comment.html', args)    

def search_titles(request):
    articles = SearchQuerySet().autocomplete(content_auto=request.POST.get('search_text', ''))            
    
    return render_to_response('ajax_search.html', {'articles' : articles})

article/templates/add_comment.html
{% extends "base.html" %}

{% block sidebar %}
<ul>
    <li><a href="/articles/get/{{article.id}}">Cancel</a></li>
</ul>
{% endblock %}

{% block content %}

<form action="/articles/add_comment/{{article.id}}/" method="post">{% csrf_token %}
<ul>
{{form.as_ul}}
</ul>

<input type="submit" name="submit" value="Post Comment">
</form>

{% endblock %}

article/templates/ajax_search.html
{% if articles.count > 0 %}

{% for article in articles %}
    <li><a href="{{ article.object.get_absolute_url }}">{{ article.object.title }}</a></li>
{% endfor %}

{% else %}

<li>None to show!</li>

{% endif %}

article/templates/article.html
{% extends "base.html" %}
{% load static %}

{% block sidebar %}
<ul>
    <li><a href="/articles/all">Articles</a></li>
</ul>
{% endblock %}

{% block content %}

<h1>{{ article.title }}</h1>
<p>{{ article.body }}</p>
{% if article.thumbnail %}
<p><img src="{% get_static_prefix %}{{article.get_thumbnail}}" width="200"/></p>
{% endif %}
<p>{{article.likes}} people liked this article</a></p>
<p><a href="/articles/like/{{article.id}}">Like</a></p>

<h2>Comments</h2>
{% for c in article.comment_set.all %}
<p>{{c.name}}: {{c.body}}</p>
{% endfor %}

<p><a href="/articles/add_comment/{{article.id}}">Add Comment</a></p>

{% endblock %}

article/templates/articles.html
{% extends "base.html" %}
{% load article_tags %}

{% block sidebar %}
<ul>
    <li><a href="/articles/all">Articles</a></li>
    <li><a href="/articles/create">Create Article</a></li>
</ul>

<h3>Search</h3>
{% csrf_token %}
<input type="text" id="search" name="search" />

<ul id="search-results">

</ul>

{% endblock %}

{% block content %}

<h2>Language is: {{language}}</h2>

<h2>Session Language is: {{session_language}}</h2>

{% if articles.count > 0 %}

{% for article in articles %}
<div>
<h2><a href="/articles/get/{{ article.id }}/">{{ article.title }}</a></h2>
<p>{{ article.body|lower|article_shorten_body:50 }}</p>
<p>{{article.likes}} people liked this article</a></p>
</div>
{% endfor %}

{% else %}

<p>None to show!</p>

{% endif %}

{% endblock %}

article/templates/create_article.html
{% extends "base.html" %}

{% block sidebar %}
<ul>
    <li><a href="/articles/all">Cancel</a></li>
</ul>
{% endblock %}

{% block content %}

<form action="/articles/create/" method="post" enctype="multipart/form-data">{% csrf_token %}
<ul>
{{form.as_ul}}
</ul>

<input type="submit" name="submit" value="Create Article">
</form>

{% endblock %}